version: '3.5'

services:
  php:
    build:
      context: ./docker/php
    image: ${REGISTRY_URL}marm-app-q2a
    container_name: marm-app-q2a
    environment:
      - PHP_IDE_CONFIG=serverName=localhost
    volumes:
      - .:/var/www/app
    networks:
      - marm-q2a
    depends_on:
      - db
    restart: always

  nginx:
    build: ./docker/nginx
    image: ${REGISTRY_URL}marm-server-q2a
    container_name: marm-server-q2a
    volumes:
      - .:/var/www/app
    ports:
      - "80"
    depends_on:
      - php
    networks:
      - marm-q2a
      - marm-router
    labels:
      - "traefik.frontend.rule=Host:dev.q2a.blackhole.marm.altarix.org"
      - "traefik.docker.network=marm-router"
    restart: always

  db:
    image: mysql
    container_name: q2a-mysql
    command: --default-authentication-plugin=mysql_native_password --max-allowed-packet=16M
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=q2a
    ports:
      - "3306:3306"
    networks:
      - marm-q2a
    volumes:
      - q2a-db:/var/lib/mysql
    restart: always

networks:
  marm-router:
    external: true
  marm-q2a:
    ipam:
      config:
        - subnet: "172.40.0.0/24"
    name: marm-q2a

volumes:
  q2a-db:
