version: '3.5'

services:
  php:
    build:
      context: ./docker/php
    image: ${REGISTRY_URL}app-q2a
    container_name: app-q2a
    environment:
      - PHP_IDE_CONFIG=serverName=localhost
    volumes:
      - .:/var/www/app
    networks:
      - q2a
    depends_on:
      - db
    restart: always

  nginx:
    build: ./docker/nginx
    image: ${REGISTRY_URL}server-q2a
    container_name: server-q2a
    volumes:
      - .:/var/www/app
    ports:
      - "80"
    depends_on:
      - php
    networks:
      - q2a
    restart: always

  db:
    image: mysql
    container_name: q2a-mysql
    command: --default-authentication-plugin=mysql_native_password --max-allowed-packet=16M
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=q2a
    ports:
      - "3306:3306"
    networks:
      - q2a
    volumes:
      - q2a-db:/var/lib/mysql
    restart: always

networks:
  q2a:
    ipam:
      config:
        - subnet: "172.40.0.0/24"
    name: q2a

volumes:
  q2a-db:
